# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Scraper": "00_scraper.ipynb",
         "Scraper.get_facebook_posts": "00_scraper.ipynb",
         "print_something": "00_scraper.ipynb"}

modules = ["scraper.py"]

doc_url = "https://devacto.github.io/talk_like/"

git_url = "https://github.com/devacto/talk_like/tree/master/"

def custom_doc_links(name): return None
