# AUTOGENERATED! DO NOT EDIT! File to edit: 00_scraper.ipynb (unless otherwise specified).

__all__ = ['Scraper', 'print_something']

# Cell

class Scraper:
    def __init__(self, username=''):
        self.username = username

# Cell
from fastcore.foundation import patch
from facebook_scraper import get_posts

@patch
def get_facebook_posts(self:Scraper):
    return get_posts(self.username)

# Cell

def print_something():
    print('something here')